import type { LevelDef } from "./types";

export const LEVELS: LevelDef[] = [
  {
    id: 1,
    title: "Voda v kotle",
    subtitle: "Najprv voda, až potom oheň",
    brief: "Kotol je skoro prázdny. Doplň vodu do zelenej zóny a nechaj ju tam chvíľu stáť.",
    physics:
      "Voda prenáša teplo. Prázdne teleso sa prehreje, lebo kov nemá čo chladiť. Priveľa vody zase nechá málo miesta na paru.",
    wrong: "Keď ostane prázdny, kúrenie je nebezpečné. Keď pretečie, voda ide tam, kde nemá.",
    why: "Kotol nie je hrniec na oheň. Voda v tele je pracovná náplň — berie teplo z výmenníka a nesie ho ďalej. Preto sa hladina drží v pásme, nie na nule a nie po okraj.",
    lesson: "Kotol nie je len oheň. Najprv musí byť voda — inak teplo nemá kam ísť.",
    controls: ["water"],
    gauges: ["water"],
    initialControls: {},
    initialSim: { waterLevel: 0.11 },
    win: { water: [0.46, 0.74], holdSec: 2.2 },
    scoring: false,
  },
  {
    id: 2,
    title: "Plyn a horák",
    subtitle: "Bez paliva niet tepla",
    brief: "Voda je v poriadku. Otvor plyn a zapáľ horák. Chceme vidieť stály plameň.",
    physics:
      "Teplo vzniká spaľovaním paliva. Plyn sám od seba nehorí — treba zážih. Bez plynu horák len ticho stojí.",
    wrong: "Veľa plynu bez zážihu nič nezohreje. Horák bez vody nespúšťame.",
    why: "Horák je miesto, kde sa plyn stretne s iskroou. Oheň je chemická reakcia, nie vypínač tepla. Preto: voda pripravená, plyn otvorený, potom zážih.",
    lesson: "Bez paliva nie je teplo. Plyn privedieme k horáku a zapálime.",
    controls: ["water", "gas", "ignite"],
    gauges: ["water", "temp"],
    initialControls: { gasOpen: 0 },
    initialSim: { waterLevel: 0.58, temperature: 24 },
    locked: { airFlow: 0.58, chimneyDraft: 0.5 },
    win: { water: [0.35, 0.85], flameMin: 0.28, holdSec: 2.4 },
    scoring: false,
  },
  {
    id: 3,
    title: "Vzduch a spaľovanie",
    subtitle: "Oheň dýcha",
    brief: "Horák horí, ale dusí sa. Uprav vzduch tak, aby dym klesol a plameň bol pokojný.",
    physics:
      "Spaľovanie potrebuje kyslík. Málo vzduchu = žltý dymivý plameň. Veľa vzduchu = studený, bledý plameň a straty.",
    wrong: "Necháš-li vzduchák na nule, kotol čmudi. Natiahneš-li ho naplno, ohrievaš komín.",
    why: "Správny pomer plyn/vzduch je ako dych pri ohni. Chceme čistý, takmer modrý plameň — nie kopcovitý žltý a nie vyfúkaný bledý.",
    lesson: "Oheň potrebuje palivo, vzduch a odvod dymu. Zlý pomer = dym alebo plytvanie.",
    controls: ["water", "gas", "air", "ignite"],
    gauges: ["water", "temp", "smoke", "efficiency"],
    initialControls: { gasOpen: 0.58, airFlow: 0.05 },
    initialSim: { waterLevel: 0.58, ignited: true, temperature: 42 },
    locked: { chimneyDraft: 0.5 },
    win: { flameMin: 0.2, smokeMax: 0.32, efficiencyMin: 0.5, holdSec: 2.6 },
    scoring: false,
  },
  {
    id: 4,
    title: "Dymák a ťah",
    subtitle: "Spaliny patria do komína",
    brief: "Kotolňa sa zadymuje. Ťah komína je skoro zatvorený. Nastav ho tak, aby dym šiel hore — ale nie naplno.",
    physics:
      "Ťah odsáva spaliny. Slabý ťah tlačí dym dnu. Priveľký ťah vyťahuje teplo do komína skôr, než zohreje vodu.",
    wrong: "Zatvorený ťah = dym v miestnosti. Vyhnaný ťah = straty a horšia účinnosť.",
    why: "Komín je pľúca kotla naruby: vydychuje spaliny. Stredný ťah drží plameň čistý a teplo v vode. Krajné polohy trestať dymom alebo únikom tepla.",
    lesson: "Ťah komína musí odviesť dym, nie ukradnúť teplo.",
    controls: ["water", "gas", "air", "draft", "ignite"],
    gauges: ["water", "temp", "smoke", "efficiency"],
    initialControls: { gasOpen: 0.55, airFlow: 0.55, chimneyDraft: 0.04 },
    initialSim: { waterLevel: 0.6, ignited: true, temperature: 48 },
    win: { flameMin: 0.18, roomSmokeMax: 0.14, smokeMax: 0.34, efficiencyMin: 0.52, holdSec: 2.8 },
    scoring: true,
  },
  {
    id: 5,
    title: "Teplo do radiátorov",
    subtitle: "Nestačí horieť",
    brief: "Kotol horí, izby sú studené. Zapni obehové čerpadlo a dostaň vodu v okruhu nad 48 °C.",
    physics:
      "Čerpadlo nosí horúcu vodu do radiátorov a studenú vracia do kotla. Bez obehu sa kotol prehrieva a radiátory spia.",
    wrong: "Keď čerpadlo stoji, teplota v kotle stúpa a okruh ostáva studený.",
    why: "Úlohou kotolne nie je mať pekný oheň, ale dodať teplo tam, kde ľudia sú. Obeh je most medzi horákom a miestnosťou.",
    lesson: "Nestačí horieť. Teplo treba odviesť — čerpadlom do okruhu.",
    controls: ["water", "gas", "air", "draft", "pump", "ignite"],
    gauges: ["temp", "circuit", "water", "pressure"],
    initialControls: { gasOpen: 0.62, airFlow: 0.58, chimneyDraft: 0.5, pumpOn: false },
    initialSim: { waterLevel: 0.6, ignited: true, temperature: 68, circuitTemp: 19 },
    win: { pumpOn: true, circuitTemp: [44, 88], water: [0.3, 0.88], pressure: [0.9, 2.6], holdSec: 2.6 },
    scoring: true,
  },
  {
    id: 6,
    title: "Tlak a poistka",
    subtitle: "Keď teplo nemá kam ísť",
    brief: "Oheň je silný, čerpadlo vypnuté, tlak rastie. Dostaň tlak do 1,2–2,3 baru a drž ho tam. Poistka je záchrana, nie cieľ.",
    physics:
      "V uzavretom systéme rastie s teplotou aj tlak. Odvod tepla (obeh) tlak krotí. Poistný ventil otvorí, až keď je neskoro na pohodu.",
    wrong: "Necháš-li horieť naplno bez obehu, poistka pufne. To je fail — nie trik.",
    why: "Tlak je správa o tom, či má para a horúca voda kam ísť. Bezpečný kotolník najprv zníži záťaž a zapne odvod, nie čaká na poistku.",
    lesson: "Vysoká teplota + uzavretý odvod = rastie tlak. Poistka je posledná záchrana.",
    controls: ["water", "gas", "air", "draft", "pump", "ignite"],
    gauges: ["temp", "pressure", "water", "circuit"],
    initialControls: { gasOpen: 0.85, airFlow: 0.6, chimneyDraft: 0.48, pumpOn: false },
    initialSim: { waterLevel: 0.62, ignited: true, temperature: 88, circuitTemp: 20 },
    win: { pressure: [1.12, 2.4], water: [0.3, 0.88], pumpOn: true, holdSec: 3 },
    scoring: true,
  },
  {
    id: 7,
    title: "Porucha: zadymenie",
    subtitle: "Nájdi príčinu, nielen dym",
    brief: "Kotol čmudi, hoci plyn ide. Skontroluj vzduch, ťah a výmenník. Špinu treba aj vyčistiť — samotné slajdre nestačia.",
    physics:
      "Dym vzniká, keď sa palivo nespáli dočista, ťah nesaje, alebo výmenník sadze berú cestu spalinám.",
    wrong: "Točiť len jedným gombíkom, keď je výmenník čierny, dym neodstráni.",
    why: "Diagnostika ide od ľahkého k ťažšiemu: vzduch, ťah, až potom špina. Keď zmes aj ťah sedia a dym ostáva, je čas na čistenie — nie na silnejší oheň.",
    lesson: "Dym je správa. Čítaj ju: vzduch, ťah, alebo špinavý výmenník.",
    controls: ["water", "gas", "air", "draft", "ignite", "clean", "pump"],
    gauges: ["smoke", "temp", "efficiency", "water"],
    initialControls: { gasOpen: 0.6, airFlow: 0.58, chimneyDraft: 0.52, pumpOn: true },
    initialSim: {
      waterLevel: 0.6,
      ignited: true,
      temperature: 55,
      circuitTemp: 40,
      dirtyExchanger: true,
    },
    win: { smokeMax: 0.28, flameMin: 0.16, dirtyCleared: true, roomSmokeMax: 0.16, holdSec: 2.6 },
    scoring: true,
  },
  {
    id: 8,
    title: "Porucha: kotol nehreje",
    subtitle: "Reťaz tepla má viac článkov",
    brief: "Radiátory sú ľadové. Prejdi reťaz: hladina, plyn, zážih, termostat, čerpadlo. Oprav všetko, čo nesedí.",
    physics:
      "Teplo vznikne len keď je voda, palivo, iskra a povolený termostat. Do izby sa dostane len cez obeh.",
    wrong: "Zapaľovať nasucho alebo točiť čerpadlo bez ohňa problém nerieši.",
    why: "Keď kotol „negreje“, pýtame sa postupne: je voda? Ide plyn? Chytá iskra? Neprevádzal termostat? Točí čerpadlo? Jeden vypadnutý článok zhodí celú reťaz.",
    lesson: "Nehreje? Skontroluj vodu, plyn, iskru, termostat a čerpadlo — v tomto poradí.",
    controls: ["water", "gas", "air", "draft", "pump", "ignite", "thermostat"],
    gauges: ["water", "temp", "circuit", "pressure"],
    initialControls: {
      gasOpen: 0,
      airFlow: 0.55,
      chimneyDraft: 0.5,
      pumpOn: false,
      thermostat: 28,
    },
    initialSim: { waterLevel: 0.16, ignited: false, temperature: 21, circuitTemp: 16 },
    win: {
      water: [0.4, 0.8],
      flameMin: 0.18,
      pumpOn: true,
      circuitTemp: [40, 88],
      holdSec: 3.2,
    },
    scoring: true,
  },
  {
    id: 9,
    title: "Majster účinnosti",
    subtitle: "Teplo za málo paliva",
    brief: "Udrž okruh medzi 52 a 70 °C s čistým plameňom. Čím vyššia účinnosť a nižšia spotreba, tým lepšie skóre.",
    physics:
      "Účinnosť rastie pri dobrom pomere plyn/vzduch, strednom ťahu, obehu a stabilnej teplote. Plytvanie je veľký oheň a otvorený komín.",
    wrong: "Naplno plyn aj ťah zohreje komín, nie školu.",
    why: "Dobrý kotolník nekúri na maximum. Kúri toľko, koľko okruh unesie, a zmes drží čistú. Úspora je dôsledok poriadku, nie šetrenia na bezpečnosti.",
    lesson: "Účinnosť je pokojný plameň, rozumný ťah a teplo, ktoré ostane v vode.",
    controls: ["water", "gas", "air", "draft", "pump", "ignite", "thermostat"],
    gauges: ["temp", "circuit", "efficiency", "smoke", "pressure"],
    initialControls: {
      gasOpen: 0.9,
      airFlow: 0.15,
      chimneyDraft: 0.92,
      pumpOn: true,
      thermostat: 78,
    },
    initialSim: { waterLevel: 0.58, ignited: true, temperature: 50, circuitTemp: 28 },
    win: {
      circuitTemp: [48, 74],
      efficiencyMin: 0.52,
      smokeMax: 0.3,
      pressure: [0.95, 2.5],
      water: [0.35, 0.85],
      holdSec: 4.5,
    },
    scoring: true,
    timeLimitSec: 180,
  },
  {
    id: 10,
    title: "Záverečná skúška",
    subtitle: "Celá kotolňa v jednom dychu",
    brief: "Systém je v rozklade: málo vody, zatvorený plyn, zlý vzduch aj ťah, čerpadlo stoji. Uveď kotol do bezpečnej, účinnej prevádzky.",
    physics:
      "Všetky časti musia hrať spolu: voda, palivo, vzduch, ťah, obeh, tlak. Jedna chyba kazí zvyšok.",
    wrong: "Zážihať nasucho alebo hnať tlak poistkou skúšku ukončí.",
    why: "Kotolník junior vie poradie: voda, plyn, vzduch, ťah, zážih, obeh. A vie, kedy spomaliť, lebo meráky hovoria alarm.",
    lesson: "Kotol nie je len oheň. Oheň potrebuje palivo, vzduch a odvod dymu — a vodu, ktorá teplo odnesie.",
    controls: ["water", "gas", "air", "draft", "pump", "ignite", "thermostat"],
    gauges: ["water", "temp", "circuit", "pressure", "smoke", "efficiency"],
    initialControls: {
      gasOpen: 0,
      airFlow: 0.08,
      chimneyDraft: 0.06,
      pumpOn: false,
      thermostat: 70,
    },
    initialSim: { waterLevel: 0.14, ignited: false, temperature: 20, circuitTemp: 16 },
    win: {
      water: [0.45, 0.75],
      flameMin: 0.16,
      pumpOn: true,
      circuitTemp: [44, 82],
      smokeMax: 0.32,
      efficiencyMin: 0.48,
      pressure: [1.0, 2.45],
      holdSec: 4,
    },
    scoring: true,
    timeLimitSec: 210,
  },
  {
    id: 11,
    title: "Zima v škole",
    subtitle: "Rýchlo, ale s rozumom",
    bonus: true,
    brief: "Po víkende je škola studená. Zohrej okruh aspoň na 62 °C, no tlak drž pod 2,4 baru a bez dymu v kotolni.",
    physics:
      "Rýchle kúrenie láká na plný plyn. Fyzika sa nemení: voda, zmes, ťah, obeh. Náraz bez odvodu zdvihne tlak.",
    wrong: "Naplno bez čerpadla zohreje kotol, nie triedy — a poistka to vypne.",
    why: "Zima chce výkon, nie chaos. Najprv voda a obeh, potom plyn. Teplo v radiátoroch je rýchlejšie, ako sa zdá, keď obeh beží.",
    lesson: "Rýchlo kúriť znamená kúriť v celom okruhu, nie len v kotle.",
    controls: ["water", "gas", "air", "draft", "pump", "ignite", "thermostat"],
    gauges: ["temp", "circuit", "pressure", "smoke", "water"],
    initialControls: {
      gasOpen: 0,
      airFlow: 0.5,
      chimneyDraft: 0.5,
      pumpOn: false,
      thermostat: 80,
    },
    initialSim: { waterLevel: 0.5, ignited: false, temperature: 16, circuitTemp: 12 },
    win: {
      circuitTemp: [62, 88],
      pressure: [1.0, 2.4],
      roomSmokeMax: 0.15,
      water: [0.35, 0.85],
      pumpOn: true,
      holdSec: 3.5,
    },
    scoring: true,
    timeLimitSec: 150,
  },
  {
    id: 12,
    title: "Nočná úspora",
    subtitle: "Ticho a málo paliva",
    bonus: true,
    brief: "Noc. Drž okruh medzi 38 a 50 °C s účinnosťou aspoň 55 %. Veľký oheň je zbytočný.",
    physics:
      "Udržať teplotu stojí menej paliva ako ju znova dvíhať. Malý čistý plameň + obeh = nočný režim.",
    wrong: "Vypnúť všetko a ráno hnať naplno spotrebuje viac, ako tichý nočný oheň.",
    why: "Úspora nie je zima. Je to najmenší oheň, ktorý ešte drží zadané pásmo. Termostat a plyn sedia nízko, zmes ostáva čistá.",
    lesson: "Šetriť palivo znamená kúriť presne toľko, koľko budova potrebuje.",
    controls: ["water", "gas", "air", "draft", "pump", "ignite", "thermostat"],
    gauges: ["circuit", "efficiency", "temp", "smoke"],
    initialControls: {
      gasOpen: 0.88,
      airFlow: 0.88,
      chimneyDraft: 0.85,
      pumpOn: true,
      thermostat: 78,
    },
    initialSim: { waterLevel: 0.6, ignited: true, temperature: 64, circuitTemp: 58 },
    win: {
      circuitTemp: [38, 50],
      efficiencyMin: 0.55,
      smokeMax: 0.26,
      pumpOn: true,
      holdSec: 6,
    },
    scoring: true,
    timeLimitSec: 160,
  },
  {
    id: 13,
    title: "Falošný alarm",
    subtitle: "Merák nie je vždy pravda",
    bonus: true,
    brief: "Alarm kričí, že kotol je prázdny. Pozri na vodoznak. Ak je voda viditeľná, over snímač — nediaľuj naslepo.",
    physics:
      "Snímače sa kazia. Kotolník verí dvom nezávislým znakom: meráku aj sklenenému vodoznaku. Doplňať plný kotol je horšie ako skontrolovať kábel.",
    wrong: "Naliať vodu len podľa červeného svetla môže kotol preplniť.",
    why: "Falošný alarm sa odhalí porovnaním. Vodoznak ukazuje skutočnú hladinu. Keď sedí a merák nie, snímač ide na kontrolu — oheň sa zbytočne netrasie.",
    lesson: "Alarm je pozvánka pozrieť sa, nie slepý rozkaz. Over to druhým znakom.",
    controls: ["water", "gas", "air", "draft", "pump", "ignite", "sensor"],
    gauges: ["water", "temp", "pressure", "circuit"],
    initialControls: {
      gasOpen: 0.5,
      airFlow: 0.55,
      chimneyDraft: 0.5,
      pumpOn: true,
      thermostat: 68,
    },
    initialSim: {
      waterLevel: 0.62,
      ignited: true,
      temperature: 58,
      circuitTemp: 46,
      falseAlarm: true,
    },
    win: {
      sensorChecked: true,
      water: [0.4, 0.8],
      flameMin: 0.15,
      pumpOn: true,
      holdSec: 2.5,
    },
    scoring: true,
  },
];

export const MAIN_COUNT = 10;
export const LAST_MAIN = 10;

export function getLevel(id: number): LevelDef {
  const level = LEVELS.find((l) => l.id === id);
  if (!level) throw new Error(`Level ${id} missing`);
  return level;
}
